- name: Run WooCommerce Price Update
        env:
          WOOCOMMERCE_URL: ${{ secrets.URL_SITE }}
          WOO_CONSUMER_KEY: ${{ secrets.WOO_CONSUMER_KEY }}
          WOO_CONSUMER_SECRET: ${{ secrets.WOO_CONSUMER_SECRET }}
          DRIVE_ID_PROD: ${{ secrets.DRIVE_ID_PROD }}
        run: |
          python 04_mise_a_jour_prix_site.py
